name: "patchworks"
description: "sync your repository with updates from its template source"
author: "ludicrous"

runs:
  using: "composite"
  steps:
    - name: TODO
      shell: bash
      run: echo "TODO"

branding:
  icon: "copy"
  color: "green"
