name: "patchworks"
description: "sync your repository with updates from its template source"
author: "ludicrous"

runs:
  using: "node20"
  main: "dist/action/index.cjs"

branding:
  icon: "copy"
  color: "green"
