name: Autofix

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  autofix:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run fixers and rebuild action bundle
        run: |
          pnpm run test:lint
          pnpm run test:pretty
          pnpm run build
      - name: Stage compiled action bundle
        run: git add dist/action/index.cjs dist/action/index.cjs.map || true
      - name: Commit fixes with autofix.ci
        uses: autofix-ci/action@v1
        with:
          commit-message: "chore: apply autofix"
