name: pkg.pr.new

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

env:
  TURBO_TELEMETRY_DISABLED: "1"

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check package
        run: bun run check

      - name: Publish preview package
        run: bun run preview:publish
